name: Swipe-File-Scout

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: pip install requests vaderSentiment python-dotenv

      - name: Run scout
        env:
          FB_TOKEN:      ${{ secrets.FB_TOKEN }}
          REDDIT_ID:     ${{ secrets.REDDIT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          EMAIL_FROM:    ${{ secrets.EMAIL_FROM }}
          EMAIL_PW:      ${{ secrets.EMAIL_PW }}
          EMAIL_TO:      ${{ secrets.EMAIL_TO }}
        run: python scout.py