name: Swipe-File-Scout

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevent hanging workflows

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests vaderSentiment python-dotenv beautifulsoup4

      - name: Run swipe-file scout
        env:
          FB_TOKEN:      ${{ secrets.FB_TOKEN }}
          REDDIT_ID:     ${{ secrets.REDDIT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          EMAIL_FROM:    ${{ secrets.EMAIL_FROM }}
          EMAIL_PW:      ${{ secrets.EMAIL_PW }}
          EMAIL_TO:      ${{ secrets.EMAIL_TO }}
        run: python scout.py

      - name: Log completion
        if: always()
        run: echo "Swipe-file scout completed at $(date)"
